### ISSUE TITLE
[hidden]

### ISSUE THREAD

**Issue by quadrupleslap** [sbhs-forkbombers/sbhs-timetable-android#19]
[hidden]

**Comment by gnustomp** [comment]
If you think there is a security issue, please contact us directly.
sbhstimetable@gmail.com works.

**Comment by keepcalm444** [comment]
Given that you haven't emailed, I'll just put my logic here:
1. Any security measures (even if not pushed to this git repository/kept hidden somehow) can be reverse-engineered in like 10 seconds using a bytecode decompiler and the APK downloaded from the Play Store

2. If it happens *automatically* in *a different app* your phone is really shifty and sharing WebView cookies between apps. That's not our problem, and also something that you should tell your OEM to fix their software.

3. If you're typing in your ID number/password into random login screens in random apps, you're *really dumb*.

4. If you're giving superuser access to random apps so that they can steal your session ID from our app, you're *really dumb*

**Comment by quadrupleslap** [comment]
ksoz. It's just that an obfuscated (or even non-obfuscated) bytecode / ndk'd x86 client secret with only https://invalid/ registered as a redirect uri would (imo) be more secure than an oauth2 proxy that allows all clients and serves only to hide the secret.

also, my reasoning was that someone as evil and stupid as me could compile a malicious clone of your app that would work perfectly, and add in a little post to another server so i can steal everyone's timetables (mwahahahaha), and no one would be able to tell the difference. on the other hand, if you had some sort of client verification or even embedded the secret, this would be much more secure, and people could rest at ease knowing that their timetables were that much safer.

at least timetables are more important than children's card games.

**Comment by gnustomp** [comment]
The problem with that is, the embedded secret is inherently insecure. And I don't know of a form of client verification that would be secure and fulfill this purpose. We could have a mechanism to identify applications accessing -node, but to they still come from the same applications on the SBHS side of things.

The obvious solution is to have the user not be an idiot and install only from a trusted source (Google Play) or compile their own version (as they would with any other application).
Additionally, distributing modified versions without source code is in violation of the terms of the AGPL 3.0 anyway.

**Comment by quadrupleslap** [comment]
but a proxy anyone can access is just as insecure as embedding the secret, and quite a bit slower. also, decompiling the bytecode takes effort, unlike simply slotting in a proxy address that's ready for abuse. oauth2 proxies fail when the user is using a malicious UA, because page loads are easy to intercept.

and tbh, even if source was released people would still download it. i mean, they won't check github first to see if someone will steal their data.

**Comment by keepcalm444** [comment]
Eh we can report your app on the play store/report you to the trained hamsters

**Comment by quadrupleslap** [comment]
lol open source fanatics relying on centralisation to hide a hole in their app.

**Comment by gnustomp** [comment]
More like, working around a limitation of the authentication process.
